spring.application.name=Employee-Management
server.port=
spring.datasource.url=
spring.datasource.driverClassName=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
jwt.expiration=90000000
jwt.refresh-expiration=60480000000000

spring.data.redis.host=localhost
spring.data.redis.port=6379